/**
 * Test youtubei.js transcript fetching directly (bypass our API).
 */
import { Innertube, UniversalCache } from 'youtubei.js';

async function test() {
  const yt = await Innertube.create({ cache: new UniversalCache(true) });

  const testIds = [
    'dQw4w9WgXcQ',  // Rick Astley (control)
    'R8rLV9PhQg0',  // Tom Lembong
    'u4ZoJKF_VuA',  // Simon Sinek TED
    'kYfNvmF0pBc',  // TED How to speak
    'UF8uR6Z6KLc',  // Steve Jobs
  ];

  let working = 0;
  for (const id of testIds) {
    try {
      console.log(`\n=== Testing ${id} ===`);
      const info = await yt.getInfo(id);
      const title = info.basic_info.title?.toString() || 'Unknown';
      console.log(`Title: ${title}`);

      const captions = info.captions;
      if (captions?.captionTracks && captions.captionTracks.length > 0) {
        console.log(`Caption tracks: ${captions.captionTracks.length}`);
        for (const ct of captions.captionTracks) {
          console.log(`  lang=${ct.languageCode} ${ct.isAutoGenerated ? '(ASR)' : '(manual)'}`);
        }

        const track = captions.captionTracks[0];
        const transcript = await track.fetchTranscript();
        console.log(`Transcript lines: ${transcript?.length || 0}`);
        if (transcript && transcript.length > 0) {
          const firstText = transcript[0].text?.toString() || '';
          console.log(`First: [${transcript[0].start}s] ${firstText.slice(0, 100)}`);
          working++;
        }
      } else {
        console.log('No caption tracks');
      }
    } catch (e: any) {
      console.log(`Error: ${e.message?.slice(0, 100)}`);
    }
    await new Promise(r => setTimeout(r, 2000));
  }
  console.log(`\n\n✅ ${working}/${testIds.length} videos have accessible transcripts`);
}

test().catch(console.error);
